// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX9_au7h8Wg5vNIue2RJpu_IwfFS-8EiQ',
    appId: '1:143261785897:web:982b0fe032a05359482138',
    messagingSenderId: '143261785897',
    projectId: 'cloneport-43922',
    authDomain: 'cloneport-43922.firebaseapp.com',
    storageBucket: 'cloneport-43922.appspot.com',
    measurementId: 'G-KN765JLGQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXqAklf6UqOiNuRM7tT3tyhnLbvoQH7U8',
    appId: '1:143261785897:android:ecfbc473f71623b5482138',
    messagingSenderId: '143261785897',
    projectId: 'cloneport-43922',
    storageBucket: 'cloneport-43922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0qVplqfmgMPXBQTaicF8mQl0hFze0VdE',
    appId: '1:143261785897:ios:5d9202904b6f39fa482138',
    messagingSenderId: '143261785897',
    projectId: 'cloneport-43922',
    storageBucket: 'cloneport-43922.appspot.com',
    iosClientId: '143261785897-l2u29ju192c0pc1u0gm042oj53fl1mrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCloneport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0qVplqfmgMPXBQTaicF8mQl0hFze0VdE',
    appId: '1:143261785897:ios:3100e6e700861d30482138',
    messagingSenderId: '143261785897',
    projectId: 'cloneport-43922',
    storageBucket: 'cloneport-43922.appspot.com',
    iosClientId: '143261785897-oebe9khtt3e30b3j5gm6qpbe5uo0vots.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCloneport.RunnerTests',
  );
}
